name: Develop-Pipeline
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      TEST_DATABASE_URL: ${{vars.TEST_DATABASE_URL}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      PAGE: ${{vars.PAGE}}
      PAGE_SIZE: ${{vars.PAGE_SIZE}}
      ORDERING: ${{vars.ORDERING}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
        ports:
          - 5432:5432

    steps:
      - name: Cloning the Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.1"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Run tests
        run: poetry run task test
